import { Button } from "std-widgets.slint";
import "./assets/unoestado.ttf";

export component MainWindow inherits Window { 
    default-font-family: "Uno Estado";
    default-font-size: 24px;
    icon: @image-url("assets/icon_32.png");
    title: "Bullet Heck! Launcher";

    VerticalLayout {
        Image {
            source: @image-url("assets/logo_half.gif");
            width: 400px;
            height: 225px;
        }

        Button {
            text: "Play";
        }

        Button {
            text: "Settings";
        }

        Button {
            text: "Credits";
            // clicked => { credits.show(); }
        }
    }
}